# Generated by Django 4.0.3 on 2023-03-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={},
        ),
    ]
