#base image for python 3 latest version
FROM python:3


#environmental variable so that python will print things immediately
ENV PYHTONUNBUFFERED 1


#names working directory in docker container /app
WORKDIR /app


#only copy requirements as a volume will be setup from present working directory to /app
COPY requirements.txt requirements.txt


#download all requirements
RUN pip install -r requirements.txt


#run server with python manage.py --- used for development
CMD python manage.py runserver '0.0.0.0:8000'
